/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GACLUiModule extends org.xtext.example.mydsl.ui.AbstractGACLUiModule {
	public GACLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
