grammar org.xtext.example.mydsl.GACL with org.eclipse.xtext.common.Terminals

generate gACL "http://www.xtext.org/example/mydsl/GACL"

Program:
	stmts += (Statement)*
;

Statement:
	TypeDecl
;


PType:
	type=intType | type=strType
;
terminal intType:
	'int'
;
terminal strType:
	'string'
;
TypeDecl:
	(('type' | 'Type' | 'TYPE') typename=ID) | 
	((('type' | 'Type' | 'TYPE'))? typename=ID ('=')? tpcode=typeCode )
;

typeCode:
	prm=PType
;